[pytest]
minversion = 7.0
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = src/tests
norecursedirs = Backend, node_modules
filterwarnings = 
    ignore::pytest.PytestCollectionWarning
addopts = -v --tb=short
